# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 587d48dbaba9405fa44601f8888cbaef52ff76d590a20fbbdccc8d7fe79f9396f7dc8f71813dd1be7b979bf7abfaa77a369d95b0fccd3eb0404c8911ec1a471a

test:
  secret_key_base: fa0d84df3b2ed7fef211fc6818387ecd1b04784420eee15a2772e1e7b9b6fcb9157b6d0fcc9234bcc2c5a792e836972304ffff599ed21d12581e1ce14bca887b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
